<script>
  // Create HIT vars
  let assignmentDuration = 3600;
  let description = '';
  let lifetime = 86400;
  let reward = '1';
  let title = '';
  let autoApprovalDelay = 10;
  let keywords = 'research,experiment';
  let maxAssignments = 5;
  let externalURL = 'https://something-autogenerated.netlify.com';
  let selectedQuals = [];
  const qualifications = ['> 95% Approval', 'Adult only', 'US Only', 'Masters'];

  $: externalQuestion = `
  <ExternalQuestion xmlns="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2006-07-14/ExternalQuestion.xsd">
  <ExternalURL>${externalURL}</ExternalURL>
  <FrameHeight>300</FrameHeight>
  </ExternalQuestion>`;

  // Add qualifications
  // https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_QualificationRequirementDataStructureArticle.html#CustomQualificationsandSystemQualifications

  const createHIT = async () => {
    console.log('create HIT');
    console.log(
      assignmentDuration,
      description,
      lifetime,
      reward,
      title,
      autoApprovalDelay,
      keywords,
      maxAssignments
    );
  };
</script>

<style>
  .minheight {
    min-height: 9rem !important;
  }
</style>

<div class="container">
  <form on:submit|preventDefault={createHIT}>
    <div class="columns">
      <div class="column">
        <div class="field">
          <label class="label">Title</label>
          <div class="control">
            <input type="text" class="input" bind:value={title} required />
          </div>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <label class="label">Keywords</label>
          <div class="control">
            <input type="text" class="input" bind:value={keywords} required />
            <p class="help">Comma separated with no spaces</p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <label class="label">Experiment URL</label>
          <div class="control">
            <input type="text" class="input" bind:value={externalURL} required />
          </div>
        </div>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <div class="field">
          <label class="label">Reward</label>
          <div class="control">
            <input type="text" class="input" bind:value={reward} required />
            <p class="help">Don't include $</p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <label class="label">Approval Delay</label>
          <div class="control">
            <input type="text" class="input" bind:value={autoApprovalDelay} required />
            <p class="help">In seconds</p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <label class="label">Duration</label>
          <div class="control">
            <input type="text" class="input" bind:value={assignmentDuration} required />
            <p class="help">In seconds. Default 1hr.</p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <label class="label">Lifetime</label>
          <div class="control">
            <input type="text" class="input" bind:value={lifetime} required />
            <p class="help">In seconds</p>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <label class="label">Max Assignments</label>
          <div class="control">
            <input type="text" class="input" bind:value={maxAssignments} required />
            <p class="help">Number of available HITs</p>
          </div>
        </div>
      </div>
    </div>
    <div class="columns">
      <div class="column is-narrow">
        <div class="field">
          <label class="label">Qualifications</label>
          <div class="control">
            <div class="select is-multiple minheight">
              <select multiple bind:value={selectedQuals}>
                {#each qualifications as qual}
                  <option value={qual}>{qual}</option>
                {/each}
              </select>
            </div>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="field">
          <label class="label">Description</label>
          <div class="control">
            <textarea class="textarea minheight" placeholder="" bind:value={description} required />
          </div>
        </div>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <div class="field">
          <div class="control">
            <button class="button is-success">Create HIT</button>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
